name: Deploy Update API

on:
  push:
    tags:
      - 'v*'  # 当推送版本标签时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate Update API
        run: python tools/update_manager.py
        
      - name: Deploy to Server
        run: |
          # 部署到你的服务器
          rsync -avz api/ user@your-server:/path/to/api/ 